export { default as PageHero } from "./Hero"
export { default as PageJavaScript } from "./JavaScript"
export { default as PageAPI } from "./Api"
export { default as PageMarkup } from "./Markup"
export { default as PageResults } from "./Results"
export { default as PageFooter } from "./Footer"
